[package]
name = "bit_serde"
version = "0.1.0"
edition = "2021"
 
[dependencies]
bit_serde_trait = { path = "./bit_serde_trait" }
bit_serde_macro = { path = "./bit_serde_macro" }
byteorder = "1.4" 
bitvec = "1"
