[package]
name = "bit_serde_macro"
version = "0.1.0"
edition = "2021"
 
[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = "1.0" 
bit_serde_trait = { path = "../bit_serde_trait" }
watt = "0.5"